# Change these first
owner: Fleming-IT # Your GitHub organization or username, where this repository lives
repo: fleming_status # The name of this repository

sites:
  - name: Fleming.de
    url: https://www.fleming.de
assignees:
  - AndreasTschritter
  - xharkonen
  - dudekowsky
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fleming.de
  # baseUrl: /fleming_status
  logoUrl: https://fleming.de/wp-content/uploads/2021/10/Fleming-Logo-rgb-pos.svg
  name: Status Page
  introTitle: "Fleming: Mehr als eine Bank für Heilberufe."
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  # themeUrl: https://raw.githubusercontent.com/Fleming-IT/fleming_status/master/assets/fleming.css
  theme: fleming
  favicon: https://raw.githubusercontent.com/Fleming-IT/fleming_status/master/assets/www.fleming.de.ico
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
